// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PrioritizedPlugin is an autogenerated mock type for the PrioritizedPlugin type
type PrioritizedPlugin struct {
	mock.Mock
}

// Priority provides a mock function with given fields:
func (_m *PrioritizedPlugin) Priority() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// SetPriority provides a mock function with given fields: _a0
func (_m *PrioritizedPlugin) SetPriority(_a0 int) {
	_m.Called(_a0)
}
