// Code generated by mockery 2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Push is an autogenerated mock type for the Push type
type Push struct {
	mock.Mock
}

// PushFunc provides a mock function with given fields:
func (_m *Push) PushFunc() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

type NewPushT interface {
	mock.TestingT
	Cleanup(func())
}

// NewPush creates a new instance of Push. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPush(t NewPushT) *Push {
	mock := &Push{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
