// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SyncedFolder is an autogenerated mock type for the SyncedFolder type
type SyncedFolder struct {
	mock.Mock
}
