// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VagrantConfig is an autogenerated mock type for the VagrantConfig type
type VagrantConfig struct {
	mock.Mock
}

// ConfigFunc provides a mock function with given fields:
func (_m *VagrantConfig) ConfigFunc() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
