// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	core "github.com/hashicorp/vagrant-plugin-sdk/core"
	mock "github.com/stretchr/testify/mock"
)

// CorePluginManager is an autogenerated mock type for the CorePluginManager type
type CorePluginManager struct {
	mock.Mock
}

// GetPlugin provides a mock function with given fields: pluginType
func (_m *CorePluginManager) GetPlugin(pluginType core.Type) (interface{}, error) {
	ret := _m.Called(pluginType)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(core.Type) interface{}); ok {
		r0 = rf(pluginType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(core.Type) error); ok {
		r1 = rf(pluginType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
