// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	core "github.com/hashicorp/vagrant-plugin-sdk/core"
	mock "github.com/stretchr/testify/mock"
)

// DownloaderOptions is an autogenerated mock type for the DownloaderOptions type
type DownloaderOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DownloaderOptions) Execute(_a0 *core.Downloader) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*core.Downloader) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
