// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	core "github.com/hashicorp/vagrant-plugin-sdk/core"
	mock "github.com/stretchr/testify/mock"
)

// MachineEntry is an autogenerated mock type for the MachineEntry type
type MachineEntry struct {
	mock.Mock
}

// Project provides a mock function with given fields: homePath
func (_m *MachineEntry) Project(homePath string) (core.Project, error) {
	ret := _m.Called(homePath)

	var r0 core.Project
	if rf, ok := ret.Get(0).(func(string) core.Project); ok {
		r0 = rf(homePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(homePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Valid provides a mock function with given fields: homePath
func (_m *MachineEntry) Valid(homePath string) (bool, error) {
	ret := _m.Called(homePath)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(homePath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(homePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
