// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PluginType is an autogenerated mock type for the PluginType type
type PluginType struct {
	mock.Mock
}

// PluginName provides a mock function with given fields:
func (_m *PluginType) PluginName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
