// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SyncedFolder is an autogenerated mock type for the SyncedFolder type
type SyncedFolder struct {
	mock.Mock
}
