on:
  push:
    branches:
      - test-*
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Vagrant
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Set Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Build
        run:  go build .
      - name: Vet
        run:  go vet ./...
      - name: Test
        run:  go test ./...
