on:
  push:
    branches:
      - test-*
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Vagrant
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Set Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
      - name: Build
        run:  go build .
      - name: Vet
        run:  go vet ./...
      - name: Test
        run:  go test ./...
