on:
  push:
    branches:
      - test-*
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Vagrant
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Set Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: '1.16'
      - name: Build
        run:  go build .
      - name: Vet
        run:  go vet ./...
      - name: Test
        run:  go test ./...
